import { Gender } from "types/user";
import { IClosetDataItem, Section, TypesOfClothing } from "types/closet";
import { Icomoon } from "types/icomoon";
import _uniqueId from "lodash.uniqueid";

export const closetData: Array<IClosetDataItem> = [
  {
    id: _uniqueId("clo-"),
    article: "Ankle socks",
    clo: 0.02,
    section: Section.SOCKS,
    gender: Gender.UNISEX,
    icon: Icomoon.ANKLE_SOCKS,
    clothingType: TypesOfClothing.ACCESSORIES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Sandals",
    clo: 0.02,
    section: Section.SHOES,
    gender: Gender.UNISEX,
    icon: Icomoon.SANDALS,
    clothingType: TypesOfClothing.SHOES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Shoes",
    clo: 0.02,
    section: Section.SHOES,
    gender: Gender.UNISEX,
    icon: Icomoon.SHOES,
    clothingType: TypesOfClothing.SHOES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Panty hose",
    clo: 0.02,
    section: Section.UNDERWEAR,
    gender: Gender.WOMEN,
    icon: Icomoon.PANTY_HOSE,
    clothingType: TypesOfClothing.UNDERWEAR,
  },
  {
    id: _uniqueId("clo-"),
    article: "Calf length socks",
    clo: 0.03,
    section: Section.SOCKS,
    gender: Gender.UNISEX,
    icon: Icomoon.CALF_LENGTH_SOCKS,
    clothingType: TypesOfClothing.ACCESSORIES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Women's underwear",
    clo: 0.03,
    section: Section.UNDERWEAR,
    gender: Gender.WOMEN,
    icon: Icomoon.WOMENS_UNDERWEAR,
    clothingType: TypesOfClothing.UNDERWEAR,
  },
  {
    id: _uniqueId("clo-"),
    article: "Men's underwear",
    clo: 0.04,
    section: Section.UNDERWEAR,
    gender: Gender.MEN,
    icon: Icomoon.MENS_UNDERWEAR,
    clothingType: TypesOfClothing.UNDERWEAR,
  },
  {
    id: _uniqueId("clo-"),
    article: "Knee socks (thick)",
    clo: 0.06,
    section: Section.SOCKS,
    gender: Gender.UNISEX,
    icon: Icomoon.KNEE_SOCKS_THICK,
    clothingType: TypesOfClothing.ACCESSORIES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Short shorts",
    clo: 0.06,
    section: Section.SHORTS,
    gender: Gender.UNISEX,
    icon: Icomoon.SHORT_SHORTS,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Walking shorts",
    clo: 0.08,
    section: Section.SHORTS,
    gender: Gender.UNISEX,
    icon: Icomoon.WALKING_SHORTS,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "T-shirt",
    clo: 0.08,
    section: Section.T_SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.T_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Boots",
    clo: 0.1,
    section: Section.SHOES,
    gender: Gender.UNISEX,
    icon: Icomoon.BOOTS,
    clothingType: TypesOfClothing.SHOES,
  },
  {
    id: _uniqueId("clo-"),
    article: "Sleeveless scoop-neck blouse",
    clo: 0.12,
    section: Section.TOP,
    gender: Gender.WOMEN,
    icon: Icomoon.SLEEVELESS_SCOOP_NECK_BLOUSE,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Short-sleeve knit shirt",
    clo: 0.17,
    section: Section.T_SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.SHORT_SLEEVE_KNIT_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Sleeveless short gown (thin)",
    clo: 0.18,
    section: Section.DRESS,
    gender: Gender.WOMEN,
    icon: Icomoon.SLEEVELESS_SHORT_GOWN_THIN,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Short-sleeve dress shirt",
    clo: 0.19,
    section: Section.SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.SHORT_SLEEVE_DRESS_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Sleeveless long gown (thin)",
    clo: 0.2,
    section: Section.DRESS,
    gender: Gender.WOMEN,
    icon: Icomoon.SLEEVELESS_LONG_GOWN_THIN,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Long underwear top",
    clo: 0.2,
    section: Section.UNDERWEAR,
    gender: Gender.WOMEN,
    icon: Icomoon.LONG_UNDERWEAR_TOP,
    clothingType: TypesOfClothing.UNDERWEAR,
  },
  {
    id: _uniqueId("clo-"),
    article: "Thick skirt",
    clo: 0.23,
    section: Section.SKIRT,
    gender: Gender.WOMEN,
    icon: Icomoon.THICK_SKIRT,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Long-sleeve dress shirt",
    clo: 0.25,
    section: Section.SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.LONG_SLEEVE_DRESS_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Long-sleeve flannel shirt",
    clo: 0.34,
    section: Section.SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.LONG_SLEEVE_FLANNEL_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Long-sleeve sweat shirt",
    clo: 0.34,
    section: Section.SHIRT,
    gender: Gender.UNISEX,
    icon: Icomoon.LONG_SLEEVE_SWEAT_SHIRT,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Long-sleeve long gown",
    clo: 0.46,
    section: Section.DRESS,
    gender: Gender.WOMEN,
    icon: Icomoon.LONG_SLEEVE_LONG_GOWN,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Thin trousers",
    clo: 0.15,
    section: Section.TROUSERS,
    gender: Gender.UNISEX,
    icon: Icomoon.THIN_TROUSERS,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Thick trousers",
    clo: 0.24,
    section: Section.TROUSERS,
    gender: Gender.UNISEX,
    icon: Icomoon.THICK_TROUSERS,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Sweatpants",
    clo: 0.28,
    section: Section.SPORT,
    gender: Gender.UNISEX,
    icon: Icomoon.SWEATPANTS,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Overalls",
    clo: 0.49,
    section: Section.SPECIAL,
    gender: Gender.UNISEX,
    icon: Icomoon.OVERALLS,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Thin skirt",
    clo: 0.14,
    section: Section.SKIRT,
    gender: Gender.WOMEN,
    icon: Icomoon.THIN_SKIRT,
    clothingType: TypesOfClothing.BOTTOM,
  },
  {
    id: _uniqueId("clo-"),
    article: "Single-breasted coat (thin)",
    clo: 0.36,
    section: Section.OUTERWEAR,
    gender: Gender.UNISEX,
    icon: Icomoon.SINGLE_BREASTED_COAT_THIN,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Single-breasted coat (thick)",
    clo: 0.44,
    section: Section.OUTERWEAR,
    gender: Gender.UNISEX,
    icon: Icomoon.SINGLE_BREASTED_COAT_THICK,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Double-breasted coat (thin)",
    clo: 0.42,
    section: Section.OUTERWEAR,
    gender: Gender.UNISEX,
    icon: Icomoon.DOUBLE_BREASTED_COAT_THIN,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Double-breasted coat (thick)",
    clo: 0.48,
    section: Section.OUTERWEAR,
    gender: Gender.UNISEX,
    icon: Icomoon.SINGLE_BREASTED_COAT_THICK,
    clothingType: TypesOfClothing.TOP,
  },
  {
    id: _uniqueId("clo-"),
    article: "Cap",
    clo: 0.01,
    section: Section.HAT,
    gender: Gender.UNISEX,
    icon: Icomoon.CAP,
    clothingType: TypesOfClothing.HEAD,
  },
  {
    id: _uniqueId("clo-"),
    article: "Winter hat",
    clo: 0.03,
    section: Section.HAT,
    gender: Gender.UNISEX,
    icon: Icomoon.HAT,
    clothingType: TypesOfClothing.HEAD,
  },
];
